export const mockPortfolios = [
  {
    id: '1',
    title: 'SDGs 永續發展融入幼兒園課程設計',
    category: 'dfc-sdgs',
    summary: '透過 SDGs 永續發展目標，將環境教育融入幼兒園日常課程，培養孩子從小建立環境保護意識。',
    content: '<h2>計畫背景</h2><p>本計畫旨在將聯合國永續發展目標（SDGs）融入幼兒園課程設計，讓幼兒從日常生活中認識環境永續的重要性。</p><h2>實施方式</h2><p>透過主題式教學活動，結合繪本故事、戶外探索與手作體驗，引導幼兒了解資源珍惜、生態保育等概念。</p><h2>成果亮點</h2><ul><li>開發 12 套 SDGs 主題教案</li><li>培訓 30 位幼教師資</li><li>涵蓋 5 所合作幼兒園</li></ul>',
    coverImage: 'https://picsum.photos/seed/portfolio1/800/500',
    images: [
      'https://picsum.photos/seed/p1a/800/500',
      'https://picsum.photos/seed/p1b/800/500',
    ],
    tags: ['SDGs', '環境教育', '課程設計'],
    year: 2024,
    published: true,
    order: 1,
    createdAt: { toDate: () => new Date('2024-03-15') },
    updatedAt: { toDate: () => new Date('2024-06-01') },
  },
  {
    id: '2',
    title: '社會情緒學習（SEL）教師增能工作坊',
    category: 'dfc-sel',
    summary: '辦理 SEL 社會情緒學習工作坊，提升幼教師資的情緒輔導能力，幫助幼兒建立健康的情緒表達。',
    content: '<h2>活動目的</h2><p>社會情緒學習（Social Emotional Learning, SEL）是幼兒發展的重要基石。本工作坊聚焦於提升幼教師資的情緒輔導技巧。</p><h2>課程內容</h2><p>涵蓋自我覺察、自我管理、社會覺察、人際技巧與負責任的決定等五大核心能力。</p><h2>參與成果</h2><ul><li>共計 6 場次工作坊</li><li>累計 150 位教師參與</li><li>滿意度達 95%</li></ul>',
    coverImage: 'https://picsum.photos/seed/portfolio2/800/500',
    images: [
      'https://picsum.photos/seed/p2a/800/500',
      'https://picsum.photos/seed/p2b/800/500',
    ],
    tags: ['SEL', '情緒學習', '教師增能'],
    year: 2024,
    published: true,
    order: 2,
    createdAt: { toDate: () => new Date('2024-04-10') },
    updatedAt: { toDate: () => new Date('2024-07-15') },
  },
  {
    id: '3',
    title: 'DFC 設計思考融入幼兒園教學',
    category: 'dfc-sdgs',
    summary: '運用 Design for Change（DFC）設計思考四步驟——感受、想像、實踐、分享，引導幼兒解決生活中的問題。',
    content: '<h2>DFC 四步驟</h2><p>Design for Change 鼓勵孩子運用「感受→想像→實踐→分享」四步驟，從生活中發現問題並主動解決。</p><h2>教學案例</h2><p>幼兒觀察到校園中的食物浪費問題，透過團體討論想像解決方案，最終設計了「惜食小尖兵」活動，減少午餐剩食量達 40%。</p>',
    coverImage: 'https://picsum.photos/seed/portfolio3/800/500',
    images: [],
    tags: ['DFC', '設計思考', '問題解決'],
    year: 2024,
    published: true,
    order: 3,
    createdAt: { toDate: () => new Date('2024-05-20') },
    updatedAt: { toDate: () => new Date('2024-08-01') },
  },
  {
    id: '4',
    title: '幼兒情緒繪本教學資源開發',
    category: 'dfc-sel',
    summary: '開發一系列以社會情緒學習為核心的幼兒繪本教學資源，提供教師完整的教學指引。',
    content: '<h2>開發理念</h2><p>以幼兒熟悉的生活情境為素材，創作系列情緒主題繪本，搭配教學活動設計，協助教師有系統地進行 SEL 教學。</p><h2>資源內容</h2><ul><li>8 本情緒主題繪本</li><li>配套教學指引手冊</li><li>互動式學習單</li><li>教室情緒角佈置指南</li></ul>',
    coverImage: 'https://picsum.photos/seed/portfolio4/800/500',
    images: [
      'https://picsum.photos/seed/p4a/800/500',
    ],
    tags: ['繪本', 'SEL', '教學資源'],
    year: 2025,
    published: true,
    order: 4,
    createdAt: { toDate: () => new Date('2025-01-10') },
    updatedAt: { toDate: () => new Date('2025-01-15') },
  },
  {
    id: '5',
    title: 'SDGs 親子共學環境教育營',
    category: 'dfc-sdgs',
    summary: '結合親子共學理念與 SDGs 環境教育，舉辦為期兩天的體驗營，促進家庭對永續發展的認識。',
    content: '<h2>營隊特色</h2><p>透過親子合作的戶外探索活動，讓家長與幼兒共同體驗自然生態之美，並了解人類活動對環境的影響。</p><h2>活動亮點</h2><ul><li>生態觀察闖關活動</li><li>親子手作環保小物</li><li>永續發展桌遊體驗</li><li>綠色飲食工作坊</li></ul>',
    coverImage: 'https://picsum.photos/seed/portfolio5/800/500',
    images: [
      'https://picsum.photos/seed/p5a/800/500',
      'https://picsum.photos/seed/p5b/800/500',
      'https://picsum.photos/seed/p5c/800/500',
    ],
    tags: ['SDGs', '親子共學', '環境教育'],
    year: 2025,
    published: true,
    order: 5,
    createdAt: { toDate: () => new Date('2025-02-01') },
    updatedAt: { toDate: () => new Date('2025-02-10') },
  },
  {
    id: '6',
    title: '幼兒園教師 SEL 實踐社群',
    category: 'dfc-sel',
    summary: '建立跨校幼兒園教師 SEL 實踐社群，促進經驗分享與專業成長。',
    content: '<h2>社群宗旨</h2><p>建立一個跨校、跨區的幼兒園教師專業學習社群，聚焦社會情緒學習的教學實踐，透過定期聚會、觀課與議課，提升教師的 SEL 教學能力。</p>',
    coverImage: 'https://picsum.photos/seed/portfolio6/800/500',
    images: [],
    tags: ['SEL', '教師社群', '專業發展'],
    year: 2025,
    published: true,
    order: 6,
    createdAt: { toDate: () => new Date('2025-01-20') },
    updatedAt: { toDate: () => new Date('2025-02-05') },
  },
]

export const mockNews = [
  {
    id: '1',
    title: '114 學年度計畫成果發表會即將登場',
    content: '<p>本計畫將於 2025 年 6 月 15 日舉辦 114 學年度成果發表會，歡迎各界蒞臨指導。本次發表會將展示各子計畫的執行成果，並邀請合作幼兒園分享教學實踐經驗。</p><p>活動地點：國立臺北教育大學篤行樓國際會議廳</p><p>報名方式：請於 6 月 1 日前填寫線上報名表。</p>',
    category: '活動',
    coverImage: 'https://picsum.photos/seed/news1/800/400',
    pinned: true,
    published: true,
    publishDate: { toDate: () => new Date('2025-05-01') },
    createdAt: { toDate: () => new Date('2025-05-01') },
    updatedAt: { toDate: () => new Date('2025-05-01') },
  },
  {
    id: '2',
    title: 'DFC-SDGs 教案徵選活動開始收件',
    content: '<p>為鼓勵幼教師資發展 SDGs 融入教學之創新教案，本計畫舉辦「DFC-SDGs 教案徵選」活動，歡迎全國幼兒園教師踴躍投稿。</p><ul><li>收件日期：即日起至 2025 年 4 月 30 日</li><li>徵選主題：SDGs 融入幼兒園課程設計</li><li>獎勵方式：特優 3 名、優等 5 名、佳作 10 名</li></ul>',
    category: '公告',
    coverImage: 'https://picsum.photos/seed/news2/800/400',
    pinned: false,
    published: true,
    publishDate: { toDate: () => new Date('2025-03-15') },
    createdAt: { toDate: () => new Date('2025-03-15') },
    updatedAt: { toDate: () => new Date('2025-03-15') },
  },
  {
    id: '3',
    title: 'SEL 種子教師培訓第二期錄取名單公佈',
    content: '<p>感謝各位教師踴躍報名，第二期 SEL 種子教師培訓錄取名單已公佈，請至計畫網站查詢。未錄取者將列入候補名單，若有名額釋出將依序通知。</p>',
    category: '公告',
    coverImage: null,
    pinned: false,
    published: true,
    publishDate: { toDate: () => new Date('2025-03-01') },
    createdAt: { toDate: () => new Date('2025-03-01') },
    updatedAt: { toDate: () => new Date('2025-03-01') },
  },
  {
    id: '4',
    title: '計畫團隊赴日本參訪幼兒教育機構',
    content: '<p>本計畫團隊於 2025 年 2 月赴日本東京參訪多所幼兒教育機構，學習日本在幼兒社會情緒學習及環境教育方面的先進經驗，參訪心得將於近期發表。</p>',
    category: '活動',
    coverImage: 'https://picsum.photos/seed/news4/800/400',
    pinned: false,
    published: true,
    publishDate: { toDate: () => new Date('2025-02-20') },
    createdAt: { toDate: () => new Date('2025-02-20') },
    updatedAt: { toDate: () => new Date('2025-02-20') },
  },
  {
    id: '5',
    title: '113 學年度計畫成果報告出爐',
    content: '<p>113 學年度各子計畫成果報告已彙整完成，內容涵蓋 DFC-SDGs 課程開發、SEL 教師培訓、教學資源研發等面向，歡迎下載參閱。</p>',
    category: '成果',
    coverImage: 'https://picsum.photos/seed/news5/800/400',
    pinned: false,
    published: true,
    publishDate: { toDate: () => new Date('2025-01-31') },
    createdAt: { toDate: () => new Date('2025-01-31') },
    updatedAt: { toDate: () => new Date('2025-01-31') },
  },
  {
    id: '6',
    title: '合作幼兒園教學觀摩活動圓滿落幕',
    content: '<p>本學期合作幼兒園教學觀摩活動已順利辦理完畢，共計 8 所幼兒園參與，展示了豐富多元的 DFC 教學實踐成果。感謝所有參與教師的用心準備與分享。</p>',
    category: '活動',
    coverImage: 'https://picsum.photos/seed/news6/800/400',
    pinned: false,
    published: true,
    publishDate: { toDate: () => new Date('2025-01-15') },
    createdAt: { toDate: () => new Date('2025-01-15') },
    updatedAt: { toDate: () => new Date('2025-01-15') },
  },
]

export const mockTeamMembers = [
  {
    id: '1',
    name: '張○○',
    title: '教授',
    role: '計畫主持人',
    avatar: 'https://picsum.photos/seed/team1/200/200',
    bio: '國立臺北教育大學幼兒與家庭教育學系教授，專長領域為幼兒課程設計、永續發展教育。',
    order: 1,
    visible: true,
  },
  {
    id: '2',
    name: '李○○',
    title: '副教授',
    role: '共同主持人',
    avatar: 'https://picsum.photos/seed/team2/200/200',
    bio: '國立臺北教育大學幼兒與家庭教育學系副教授，專長領域為社會情緒學習、幼兒輔導。',
    order: 2,
    visible: true,
  },
  {
    id: '3',
    name: '王○○',
    title: '助理教授',
    role: '協同主持人',
    avatar: 'https://picsum.photos/seed/team3/200/200',
    bio: '專長領域為教育科技、數位教材開發，負責計畫數位資源建置。',
    order: 3,
    visible: true,
  },
  {
    id: '4',
    name: '陳○○',
    title: '博士生',
    role: '專任助理',
    avatar: 'https://picsum.photos/seed/team4/200/200',
    bio: '國立臺北教育大學教育學系博士生，負責計畫行政事務與活動統籌。',
    order: 4,
    visible: true,
  },
  {
    id: '5',
    name: '林○○',
    title: '碩士生',
    role: '兼任助理',
    avatar: 'https://picsum.photos/seed/team5/200/200',
    bio: '負責教學資源開發與網站維護。',
    order: 5,
    visible: true,
  },
]

export const mockStats = {
  students: 500,
  projects: 120,
  partners: 30,
  years: 5,
}
